/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AlertSeverity = { 'warning' : null } |
  { 'info' : null } |
  { 'critical' : null };
export interface MarketAlert {
  'ticker' : Ticker,
  'message' : string,
  'timestamp' : Timestamp,
  'severity' : AlertSeverity,
}
export interface MarketSummary {
  'sentimentScore' : bigint,
  'marketBreadth' : number,
  'lastUpdated' : bigint,
  'topMovers' : Array<TopMover>,
}
export interface OHLC {
  'low' : number,
  'ticker' : Ticker,
  'high' : number,
  'close' : number,
  'open' : number,
  'volume' : bigint,
  'timestamp' : Timestamp,
}
export interface Prediction {
  'trend' : TrendDirection,
  'ticker' : Ticker,
  'volatility' : number,
  'signalStrength' : bigint,
  'resistanceLevel' : number,
  'supportLevel' : number,
  'timestamp' : Timestamp,
  'projection' : Array<number>,
  'confidence' : bigint,
}
export interface PredictionEntry {
  'trend' : TrendDirection,
  'ticker' : Ticker,
  'volatility' : number,
  'signalStrength' : bigint,
  'resistanceLevel' : number,
  'supportLevel' : number,
  'timestamp' : Timestamp,
  'projection' : Array<number>,
  'confidence' : bigint,
}
export type SignalDirection = { 'buy' : null } |
  { 'hold' : null } |
  { 'sell' : null };
export type Ticker = string;
export type Timestamp = bigint;
export interface TopMover {
  'ticker' : string,
  'volume' : bigint,
  'price' : number,
  'changePercent' : number,
}
export interface TradingSignal {
  'direction' : SignalDirection,
  'ticker' : Ticker,
  'strength' : number,
  'timestamp' : Timestamp,
}
export type TrendDirection = { 'bullish' : null } |
  { 'bearish' : null } |
  { 'neutral' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStats {
  'accuracyRate' : number,
  'wins' : bigint,
  'losses' : bigint,
  'totalPredictions' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addToWatchlist' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCandlestickHistory' : ActorMethod<[string], Array<OHLC>>,
  'getCurrentPrice' : ActorMethod<[string], OHLC>,
  'getLastFetchTime' : ActorMethod<[], [] | [bigint]>,
  'getMarketSummary' : ActorMethod<[Array<string>], MarketSummary>,
  'getMultiplePrices' : ActorMethod<[Array<string>], Array<[string, number]>>,
  'getPredictionHistory' : ActorMethod<[], Array<PredictionEntry>>,
  'getRecentAlerts' : ActorMethod<[], Array<MarketAlert>>,
  'getTradingSignal' : ActorMethod<[string], TradingSignal>,
  'getUserStats' : ActorMethod<[], UserStats>,
  'getWatchlist' : ActorMethod<[], Array<string>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'predict' : ActorMethod<[string], Prediction>,
  'refreshMarketData' : ActorMethod<[], undefined>,
  'removeFromWatchlist' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];