/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Ticker = IDL.Text;
export const Timestamp = IDL.Int;
export const OHLC = IDL.Record({
  'low' : IDL.Float64,
  'ticker' : Ticker,
  'high' : IDL.Float64,
  'close' : IDL.Float64,
  'open' : IDL.Float64,
  'volume' : IDL.Nat,
  'timestamp' : Timestamp,
});
export const TopMover = IDL.Record({
  'ticker' : IDL.Text,
  'volume' : IDL.Nat,
  'price' : IDL.Float64,
  'changePercent' : IDL.Float64,
});
export const MarketSummary = IDL.Record({
  'sentimentScore' : IDL.Nat,
  'marketBreadth' : IDL.Float64,
  'lastUpdated' : IDL.Int,
  'topMovers' : IDL.Vec(TopMover),
});
export const TrendDirection = IDL.Variant({
  'bullish' : IDL.Null,
  'bearish' : IDL.Null,
  'neutral' : IDL.Null,
});
export const PredictionEntry = IDL.Record({
  'trend' : TrendDirection,
  'ticker' : Ticker,
  'volatility' : IDL.Float64,
  'signalStrength' : IDL.Nat,
  'resistanceLevel' : IDL.Float64,
  'supportLevel' : IDL.Float64,
  'timestamp' : Timestamp,
  'projection' : IDL.Vec(IDL.Float64),
  'confidence' : IDL.Nat,
});
export const AlertSeverity = IDL.Variant({
  'warning' : IDL.Null,
  'info' : IDL.Null,
  'critical' : IDL.Null,
});
export const MarketAlert = IDL.Record({
  'ticker' : Ticker,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
  'severity' : AlertSeverity,
});
export const SignalDirection = IDL.Variant({
  'buy' : IDL.Null,
  'hold' : IDL.Null,
  'sell' : IDL.Null,
});
export const TradingSignal = IDL.Record({
  'direction' : SignalDirection,
  'ticker' : Ticker,
  'strength' : IDL.Float64,
  'timestamp' : Timestamp,
});
export const UserStats = IDL.Record({
  'accuracyRate' : IDL.Float64,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'totalPredictions' : IDL.Nat,
});
export const Prediction = IDL.Record({
  'trend' : TrendDirection,
  'ticker' : Ticker,
  'volatility' : IDL.Float64,
  'signalStrength' : IDL.Nat,
  'resistanceLevel' : IDL.Float64,
  'supportLevel' : IDL.Float64,
  'timestamp' : Timestamp,
  'projection' : IDL.Vec(IDL.Float64),
  'confidence' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addToWatchlist' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandlestickHistory' : IDL.Func([IDL.Text], [IDL.Vec(OHLC)], ['query']),
  'getCurrentPrice' : IDL.Func([IDL.Text], [OHLC], ['query']),
  'getLastFetchTime' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
  'getMarketSummary' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [MarketSummary],
      ['query'],
    ),
  'getMultiplePrices' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getPredictionHistory' : IDL.Func([], [IDL.Vec(PredictionEntry)], ['query']),
  'getRecentAlerts' : IDL.Func([], [IDL.Vec(MarketAlert)], ['query']),
  'getTradingSignal' : IDL.Func([IDL.Text], [TradingSignal], ['query']),
  'getUserStats' : IDL.Func([], [UserStats], ['query']),
  'getWatchlist' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'predict' : IDL.Func([IDL.Text], [Prediction], []),
  'refreshMarketData' : IDL.Func([], [], []),
  'removeFromWatchlist' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Ticker = IDL.Text;
  const Timestamp = IDL.Int;
  const OHLC = IDL.Record({
    'low' : IDL.Float64,
    'ticker' : Ticker,
    'high' : IDL.Float64,
    'close' : IDL.Float64,
    'open' : IDL.Float64,
    'volume' : IDL.Nat,
    'timestamp' : Timestamp,
  });
  const TopMover = IDL.Record({
    'ticker' : IDL.Text,
    'volume' : IDL.Nat,
    'price' : IDL.Float64,
    'changePercent' : IDL.Float64,
  });
  const MarketSummary = IDL.Record({
    'sentimentScore' : IDL.Nat,
    'marketBreadth' : IDL.Float64,
    'lastUpdated' : IDL.Int,
    'topMovers' : IDL.Vec(TopMover),
  });
  const TrendDirection = IDL.Variant({
    'bullish' : IDL.Null,
    'bearish' : IDL.Null,
    'neutral' : IDL.Null,
  });
  const PredictionEntry = IDL.Record({
    'trend' : TrendDirection,
    'ticker' : Ticker,
    'volatility' : IDL.Float64,
    'signalStrength' : IDL.Nat,
    'resistanceLevel' : IDL.Float64,
    'supportLevel' : IDL.Float64,
    'timestamp' : Timestamp,
    'projection' : IDL.Vec(IDL.Float64),
    'confidence' : IDL.Nat,
  });
  const AlertSeverity = IDL.Variant({
    'warning' : IDL.Null,
    'info' : IDL.Null,
    'critical' : IDL.Null,
  });
  const MarketAlert = IDL.Record({
    'ticker' : Ticker,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
    'severity' : AlertSeverity,
  });
  const SignalDirection = IDL.Variant({
    'buy' : IDL.Null,
    'hold' : IDL.Null,
    'sell' : IDL.Null,
  });
  const TradingSignal = IDL.Record({
    'direction' : SignalDirection,
    'ticker' : Ticker,
    'strength' : IDL.Float64,
    'timestamp' : Timestamp,
  });
  const UserStats = IDL.Record({
    'accuracyRate' : IDL.Float64,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'totalPredictions' : IDL.Nat,
  });
  const Prediction = IDL.Record({
    'trend' : TrendDirection,
    'ticker' : Ticker,
    'volatility' : IDL.Float64,
    'signalStrength' : IDL.Nat,
    'resistanceLevel' : IDL.Float64,
    'supportLevel' : IDL.Float64,
    'timestamp' : Timestamp,
    'projection' : IDL.Vec(IDL.Float64),
    'confidence' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addToWatchlist' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandlestickHistory' : IDL.Func([IDL.Text], [IDL.Vec(OHLC)], ['query']),
    'getCurrentPrice' : IDL.Func([IDL.Text], [OHLC], ['query']),
    'getLastFetchTime' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
    'getMarketSummary' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [MarketSummary],
        ['query'],
      ),
    'getMultiplePrices' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getPredictionHistory' : IDL.Func(
        [],
        [IDL.Vec(PredictionEntry)],
        ['query'],
      ),
    'getRecentAlerts' : IDL.Func([], [IDL.Vec(MarketAlert)], ['query']),
    'getTradingSignal' : IDL.Func([IDL.Text], [TradingSignal], ['query']),
    'getUserStats' : IDL.Func([], [UserStats], ['query']),
    'getWatchlist' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'predict' : IDL.Func([IDL.Text], [Prediction], []),
    'refreshMarketData' : IDL.Func([], [], []),
    'removeFromWatchlist' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };