/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface Prediction {
    trend: TrendDirection;
    ticker: Ticker;
    volatility: number;
    signalStrength: bigint;
    resistanceLevel: number;
    supportLevel: number;
    timestamp: Timestamp;
    projection: Array<number>;
    confidence: bigint;
}
export interface OHLC {
    low: number;
    ticker: Ticker;
    high: number;
    close: number;
    open: number;
    volume: bigint;
    timestamp: Timestamp;
}
export interface MarketSummary {
    sentimentScore: bigint;
    marketBreadth: number;
    lastUpdated: bigint;
    topMovers: Array<TopMover>;
}
export type Ticker = string;
export interface TradingSignal {
    direction: SignalDirection;
    ticker: Ticker;
    strength: number;
    timestamp: Timestamp;
}
export interface TopMover {
    ticker: string;
    volume: bigint;
    price: number;
    changePercent: number;
}
export interface PredictionEntry {
    trend: TrendDirection;
    ticker: Ticker;
    volatility: number;
    signalStrength: bigint;
    resistanceLevel: number;
    supportLevel: number;
    timestamp: Timestamp;
    projection: Array<number>;
    confidence: bigint;
}
export interface MarketAlert {
    ticker: Ticker;
    message: string;
    timestamp: Timestamp;
    severity: AlertSeverity;
}
export interface UserStats {
    accuracyRate: number;
    wins: bigint;
    losses: bigint;
    totalPredictions: bigint;
}
export enum AlertSeverity {
    warning = "warning",
    info = "info",
    critical = "critical"
}
export enum SignalDirection {
    buy = "buy",
    hold = "hold",
    sell = "sell"
}
export enum TrendDirection {
    bullish = "bullish",
    bearish = "bearish",
    neutral = "neutral"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addToWatchlist(ticker: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getCandlestickHistory(ticker: string): Promise<Array<OHLC>>;
    getCurrentPrice(ticker: string): Promise<OHLC>;
    getLastFetchTime(): Promise<bigint | null>;
    getMarketSummary(tickers: Array<string>): Promise<MarketSummary>;
    getMultiplePrices(tickers: Array<string>): Promise<Array<[string, number]>>;
    getPredictionHistory(): Promise<Array<PredictionEntry>>;
    getRecentAlerts(): Promise<Array<MarketAlert>>;
    getTradingSignal(ticker: string): Promise<TradingSignal>;
    getUserStats(): Promise<UserStats>;
    getWatchlist(): Promise<Array<string>>;
    isCallerAdmin(): Promise<boolean>;
    predict(ticker: string): Promise<Prediction>;
    refreshMarketData(): Promise<void>;
    removeFromWatchlist(ticker: string): Promise<void>;
}
import type { AlertSeverity as _AlertSeverity, MarketAlert as _MarketAlert, Prediction as _Prediction, PredictionEntry as _PredictionEntry, SignalDirection as _SignalDirection, Ticker as _Ticker, Timestamp as _Timestamp, TradingSignal as _TradingSignal, TrendDirection as _TrendDirection, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addToWatchlist(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWatchlist(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCandlestickHistory(arg0: string): Promise<Array<OHLC>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCandlestickHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCandlestickHistory(arg0);
            return result;
        }
    }
    async getCurrentPrice(arg0: string): Promise<OHLC> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentPrice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentPrice(arg0);
            return result;
        }
    }
    async getLastFetchTime(): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastFetchTime();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastFetchTime();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketSummary(arg0: Array<string>): Promise<MarketSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketSummary(arg0);
            return result;
        }
    }
    async getMultiplePrices(arg0: Array<string>): Promise<Array<[string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMultiplePrices(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMultiplePrices(arg0);
            return result;
        }
    }
    async getPredictionHistory(): Promise<Array<PredictionEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPredictionHistory();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPredictionHistory();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentAlerts(): Promise<Array<MarketAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentAlerts();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentAlerts();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradingSignal(arg0: string): Promise<TradingSignal> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradingSignal(arg0);
                return from_candid_TradingSignal_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradingSignal(arg0);
            return from_candid_TradingSignal_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserStats(): Promise<UserStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserStats();
            return result;
        }
    }
    async getWatchlist(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWatchlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWatchlist();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async predict(arg0: string): Promise<Prediction> {
        if (this.processError) {
            try {
                const result = await this.actor.predict(arg0);
                return from_candid_Prediction_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.predict(arg0);
            return from_candid_Prediction_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async refreshMarketData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.refreshMarketData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refreshMarketData();
            return result;
        }
    }
    async removeFromWatchlist(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWatchlist(arg0);
            return result;
        }
    }
}
function from_candid_AlertSeverity_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertSeverity): AlertSeverity {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_MarketAlert_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarketAlert): MarketAlert {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PredictionEntry_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PredictionEntry): PredictionEntry {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Prediction_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Prediction): Prediction {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_SignalDirection_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignalDirection): SignalDirection {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_TradingSignal_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradingSignal): TradingSignal {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_TrendDirection_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrendDirection): TrendDirection {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ticker: _Ticker;
    message: string;
    timestamp: _Timestamp;
    severity: _AlertSeverity;
}): {
    ticker: Ticker;
    message: string;
    timestamp: Timestamp;
    severity: AlertSeverity;
} {
    return {
        ticker: value.ticker,
        message: value.message,
        timestamp: value.timestamp,
        severity: from_candid_AlertSeverity_n14(_uploadFile, _downloadFile, value.severity)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction: _SignalDirection;
    ticker: _Ticker;
    strength: number;
    timestamp: _Timestamp;
}): {
    direction: SignalDirection;
    ticker: Ticker;
    strength: number;
    timestamp: Timestamp;
} {
    return {
        direction: from_candid_SignalDirection_n18(_uploadFile, _downloadFile, value.direction),
        ticker: value.ticker,
        strength: value.strength,
        timestamp: value.timestamp
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trend: _TrendDirection;
    ticker: _Ticker;
    volatility: number;
    signalStrength: bigint;
    resistanceLevel: number;
    supportLevel: number;
    timestamp: _Timestamp;
    projection: Array<number>;
    confidence: bigint;
}): {
    trend: TrendDirection;
    ticker: Ticker;
    volatility: number;
    signalStrength: bigint;
    resistanceLevel: number;
    supportLevel: number;
    timestamp: Timestamp;
    projection: Array<number>;
    confidence: bigint;
} {
    return {
        trend: from_candid_TrendDirection_n9(_uploadFile, _downloadFile, value.trend),
        ticker: value.ticker,
        volatility: value.volatility,
        signalStrength: value.signalStrength,
        resistanceLevel: value.resistanceLevel,
        supportLevel: value.supportLevel,
        timestamp: value.timestamp,
        projection: value.projection,
        confidence: value.confidence
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bullish: null;
} | {
    bearish: null;
} | {
    neutral: null;
}): TrendDirection {
    return "bullish" in value ? TrendDirection.bullish : "bearish" in value ? TrendDirection.bearish : "neutral" in value ? TrendDirection.neutral : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    warning: null;
} | {
    info: null;
} | {
    critical: null;
}): AlertSeverity {
    return "warning" in value ? AlertSeverity.warning : "info" in value ? AlertSeverity.info : "critical" in value ? AlertSeverity.critical : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    hold: null;
} | {
    sell: null;
}): SignalDirection {
    return "buy" in value ? SignalDirection.buy : "hold" in value ? SignalDirection.hold : "sell" in value ? SignalDirection.sell : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MarketAlert>): Array<MarketAlert> {
    return value.map((x)=>from_candid_MarketAlert_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PredictionEntry>): Array<PredictionEntry> {
    return value.map((x)=>from_candid_PredictionEntry_n7(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
